<option value="">Select</option>
<option value="France">France</option>
<option value="Italy">Italy</option>
<option value="Spain">Spain</option>
<option value="United States">United States</option>
<option value="China">China</option>
<option value="Argentina">Argentina</option>
<option value="Australia">Australia</option>
<option value="Chile">Chile</option>
<option value="South Africa">South Africa</option>
<option value="Germany">Germany</option>
<option value="Russia">Russia</option>
<option value="Portugal">Portugal</option>
<option value="Brazil">Brazil</option>
<option value="Greece">Greece</option>
<option value="Austria">Austria</option>
<option value="Serbia">Serbia</option>
<option value="New Zealand">New Zealand</option>
<option value="Hungary">Hungary</option>
<option value="Ukraine">Ukraine</option>
<option value="Romania">Romania</option>
<option value="Moldova">Moldova</option>
<option value="Bulgaria">Bulgaria</option>
<option value="Switzerland">Switzerland</option>
<option value="Georgia">Georgia</option>
<option value="Japan">Japan</option>
<option value="Peru">Peru</option>
<option value="Macedonia">Macedonia</option>
<option value="Uruguay">Uruguay</option>
<option value="Croatia">Croatia</option>
<option value="Algeria">Algeria</option>
<option value="Canada">Canada</option>
<option value="Czech Republic">Czech Republic</option>
<option value="Morocco">Morocco</option>
<option value="Slovakia">Slovakia</option>
<option value="Turkey">Turkey</option>
<option value="Mexico">Mexico</option>
<option value="Belarus">Belarus</option>
<option value="Slovenia">Slovenia</option>
<option value="Tunisia">Tunisia</option>
<option value="Uzbekistan">Uzbekistan</option>
